### ISSUE TITLE
Basic Schematic Question

### ISSUE THREAD

**Issue by singh577** [NeonHorizon/lipopi#22]
I was reading the schematics for both the basic and the power-up, power-down version in addition to this article by adafruit: https://learn.adafruit.com/raspberry-pi-wearable-time-lapse-camera?view=all#wiring
I understand the basics of reading a schematic, but is there any reason why the article above wired straight from the powerboost to the pi's GPIO's and you all used Diodes and resistors to step down the voltage?
I suspected it had to do with them using a while loop within their program to check the GPIO signals and you all used systemmd, not sure, would appreciate any info regarding this. 
Specifically, I see you had explained it was to step down the voltage, but is their approach to wiring naive or am I missing the difference in the approach?

**Comment by NeonHorizon** [comment]
I think you are getting confused between the control wires and the power wires. The power wires go direct  on our circuits as well but are not shown in the circuit diagrams. They are described in step one on the front page and can either be hooked to the test points on a Pi Zero (like in my photo), or you can hook directly to the power pins on the GPIO header (like Adafruit did) or you can use a USB cable.

The Adafruit circuit doesn't have any of the control wires as you have to manually turn the power on and off with the switch, which is why it doesn't have any diodes.
