### ISSUE TITLE
Connecting LBO directly to a GPIO pin

### ISSUE THREAD

**Issue by antfris** [NeonHorizon/lipopi#52]
@NeonHorizon I'm reading here that you can't connect the LBO directly to one of the GPIO pins:
https://forums.adafruit.com/viewtopic.php?f=8&t=73893 - and in a number of other places people are saying the same thing. 

I'm having an issue where I'm trying to emulate this on a different pin other that GPIO15, by running this:
```
echo 21 > /sys/class/gpio/export
echo "in" > /sys/class/gpio/gpio21/direction
echo 0 > /sys/class/gpio/gpio21/active_low
```

But then when I run `cat /sys/class/gpio/gpio21/value` with nothing connected I get 0, whereas wen I run `cat /sys/class/gpio/gpio15/value` and there's nothing connected, it always reads 1. 

Also, if I then plug GPIO 21 into LBO it makes the battery LED come on on the powerboost. 

Wondering if you know whether this should be the case?

Many thanks 

Anthony

**Comment by NeonHorizon** [comment]
You can connect it directly to a GPIO pin, please see this thread here which explains why there's no issue: https://github.com/NeonHorizon/lipopi/issues/2

The reason you are getting zero is GPIO 21 doesn't have the internal pullup resistor enabled by default like GPIO 15. You need to either choose a pin where you can enable the internal pull up resistor (depends on the model of Pi) or use an external pull up resistor.

The reason the LED is coming on is also because you don't have the pullup resistor enabled, so the LED is grounding through the Pi.
